package Controllers.BloodBank;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

public class BloodBankNameList {

    public static ObservableList<String> list = FXCollections.observableArrayList("AMPARA : AKKARAIPATTU", "AMPARA : AMPARA", "AMPARA : DEHIATTHAKANDIYA", "AMPARA : KALMUNAI AM(S)", "AMPARA : KALMUNAI BASE(N)",
            "AMPARA : MAHAOYA", "AMPARA : SAMMANTHURAI", "ANURADHAPURA : ANURADHAPURA", "ANURADHAPURA : PADAVIYA", "ANURADHAPURA : THAMBUTHTHEGAMA", "BADULLA : BADULLA", "BADULLA : DIYATALAWA",
            "BADULLA : MAHIYANGANAYA", "BADULLA : WELIMADA", "BATTICOLOA : BATTICALOA", "BATTICOLOA : VALACHCHENAI", "CHILAW : CHILAW", "CHILAW : KALPITIYA", "CHILAW : MARAWILA", "CHILAW : PUTTALAM",
            "CHILAW : WARAKAPOLA", "COLOMBO : ACCIDENT SERVICE", "COLOMBO : CSHW", "COLOMBO : CSTH", "COLOMBO : DMH", "COLOMBO : IDH - ANGODA", "COLOMBO : LRH", "COLOMBO : MULLERIYAWA", "COLOMBO : NBC",
            "COLOMBO : NHSL", "COLOMBO : SJGH - KOTTE", "GAMPAHA : GAMPAHA", "GAMPAHA : WATHUPITIWALA", "HAMBANTOTA : HAMBANTHOTA", "HAMBANTOTA : TANGALLE", "HAMBANTOTA : THISSAMAHARAMA", "JAFFNA : JAFFNA",
            "JAFFNA : KILLINOCHCHI", "JAFFNA : MULLAITIVU", "JAFFNA : POINT PEDRO", "JAFFNA : THELLIPPALLAI", "KALUTARA : HORANA", "KALUTARA : KALUTARA", "KALUTARA : KETHUMATHIE", "KALUTARA : PANADURA",
            "KAMBURUGAMUWA : KAMBURUGAMUWA", "KAMBURUGAMUWA : KAMBURUPITIYA", "KAMBURUGAMUWA : MATARA", "KANDY : DAMBULLA", "KANDY : KANDY", "KANDY : MATALE", "KARAPITIYA : BALAPITIYA", "KARAPITIYA : ELPITIYA",
            "KARAPITIYA : KARAPITIYA", "KARAPITIYA : MAHAMODARA", "KEGALEE : KARAWENELLA", "KEGALLE : KEGALLE", "KEGALLE : MAWANELLA", "KURUNEGALA : DAMBADENIYA", "KURUNEGALA : KULIYAPITIYA",
            "KURUNEGALA : KURUNEGALA", "KURUNEGALA : NIKAWERATIYA", "MAHARAGAMA : AVISSAWELLA", "MAHARAGAMA : CIM", "MAHARAGAMA : HOMAGAMA", "MONARAGALA : BIBILA", "MONARAGALA : MONARAGALA",
            "MONARAGALA : WELLAWAYA", "NUWARAELIYA : DIKKOYA", "NUWARAELIYA : NUWARAELIYA", "NUWARAELIYA : RIKILLAGASKADA", "PERADENIYA : GAMPOLA", "PERADENIYA : NAWALAPITIYA", "PERADENIYA : PERADENIYA",
            "POLONNARUWA : MEDIRIGIRIYA", "POLONNARUWA : POLONNARUWA", "RAGAMA : CNTH", "RAGAMA : NEGAMBO", "RAGAMA : WELISARA", "RATHNAPURA : BALANGODA", "RATHNAPURA : EMBILIPITIYA", "RATHNAPURA : KAHAWATTA",
            "RATHNAPURA : RATHNAPURA", "TRINCOMALEE : KANTALE", "TRINCOMALEE : KINNIYA", "TRINCOMALEE : MUTHUR", "TRINCOMALEE : TRINCOMALEE", "VAVUNIYA : CHETTIKULAM", "VAVUNIYA : MANNAR", "VAVUNIYA : VAVUNIYA");

    public static ObservableList<String> getList() {
        return list;
    }
}
